apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    project: frontend
    component: frontend
    environment: dev
    version: v1
  
  spec:
  containers:
  - name: frontend
    image: nginx
  
